name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      env:
        DEVELOPER_DIR: /Applications/Xcode_16.app
      run: xcodebuild test -scheme Xcodes
